#!/usr/bin/env bash
set -e

echo "Checking out nemesis : $1"
exec "git -C $NEMESIS_SRC_ROOT checkout $1"
echo "Nemesis source now at branch:"
exec "git -C $NEMESIS_SRC_ROOT rev-parse --abbrev-ref HEAD"
