#!/usr/bin/env bash
# Usage: nem re-db
# Summary: Regenerate the nemesis database (from regenerate_db.sh)

set -e

# Ensuring we stay sandboxed by clearing PYTHONPATH

if [[ -z $(ps ax | grep "[p]ostgres") ]]; then
  echo "Postgres not running"
  echo "starting postgres..."
  postgres_status=$(launchctl load -F /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist 2>&1)
  if [[ $postgres_status != *"loaded"* ]]; then
    echo "waiting for postgres..."
    sleep 2
    echo $postgres_status
  fi
fi

echo " "
echo "======================================"
echo "Generating schema..."
echo "======================================"
PYTHONPATH='' $NEMESIS_ENV_ROOT/bin/generate_schema | psql -U nemesis -d nemesis

echo " "
echo "======================================"
echo "Stamping head..."
echo "======================================"
PYTHONPATH='' $NEMESIS_ROOT/bin/alembic -c $NEMESIS_SRC_ROOT/nemesis/development.ini stamp head

echo " "
echo "======================================"
echo "Populating verticals..."
echo "======================================"
PYTHONPATH='' $NEMESIS_ENV_ROOT/bin/populate_verticals

echo " "
echo "======================================"
echo "Loading test data..."
echo "======================================"
PYTHONPATH='' $NEMESIS_ENV_ROOT/bin/load_data -t

echo " "
echo "======================================"
echo "Finished!"

if [[ $postgres_status == *"loaded"* ]]; then
  echo "stopping postgres..."
  $(launchctl unload /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist 2>&1)
fi

