#!/usr/bin/env bash
# Usage: nem checkout
# Summary: Checkout a nemesis branch
# Help: This will checkout the given git branch of the nemesis repo.

set -e

[ -f "$_NEM_ROOT/share/bash-colors" ] && . "$_NEM_ROOT/share/bash-colors"

# provide nem completions
if [ "$1" == "--complete" ]; then
    git -C $NEMESIS_SRC_ROOT branch -r | sed -e 's/^  origin\///'
    exit
fi

echo "Fetching the latest changes"
git -C $NEMESIS_SRC_ROOT fetch -p
echo "Checking out nemesis: $1"
git -C $NEMESIS_SRC_ROOT checkout $1
echo "Nemesis source now at branch: $(clr_magenta $(git -C $NEMESIS_SRC_ROOT rev-parse --abbrev-ref HEAD))"
