#!/usr/bin/env bash
# Usage: nem update [package]
# Summary: Updates the nemesis environment.
# Help: Available packages
#   nemesis
#
# Updates all parts of the nemesis environment.
#   - downloads the latest nemesis manifest (sprinter config)
#   - fetches git changes
#   - updates npm dependencies
#   - updates python dependencies
#   - updates packaged dependencies (brew / apt-get)
#   - updates the nemesis database (regenerate_db / migrations)

set -e

NL=$'\n'

# provide nem completions
if [ "$1" == "--complete" ]; then
    echo "nemesis"
    exit
fi
if [ "$1" == "nemesis" ]; then
    echo "Updating Nemesis environment from $NEMESIS_SRC_ROOT/nemesis-manifest.cfg"

    # Ensuring we stay sandboxed by resetting PYTHONPATH
    PYTHONPATH='' sprinter update nemesis
    # shift
    # exec "PYTHONPATH='' sprinter install $NEMESIS_SRC_ROOT/nemesis-manifest.cfg '$@'"
    exit 0

elif [ -n "$1" ]; then
    echo "${NL}Invalid package: '$1'"
fi
echo "${NL}Did you mean?    nem update nemesis${NL}${NL}"
nem help update
