#!/usr/bin/env bash
set -e

echo "Starting thumbor: $NEMESIS_ROOT/bin/thumbor" --conf="$NEMESIS_SRC_ROOT/thumbor/thumbor.conf.py"
exec "$NEMESIS_ROOT/bin/thumbor" --conf="$NEMESIS_SRC_ROOT/thumbor/thumbor.conf.py"
