#!/usr/bin/env bash
## Usage: nem thumbor {directoryname}
# Summary: Starts up the nemesis thumbor server.

set -e

echo "Starting thumbor: $NEMESIS_ROOT/bin/thumbor" --conf="$NEMESIS_SRC_ROOT/thumbor/thumbor.conf.py"
# Ensuring we stay sandboxed by resetting PYTHONPATH
PYTHONPATH='' $NEMESIS_ROOT/bin/thumbor --conf=$NEMESIS_SRC_ROOT/thumbor/thumbor.conf.py
