#!/usr/bin/env bash
# Usage: nem fe {directoryname}
# Summary: Starts up the nemesis front-end dev server (dev-server)

set -e

temp=`pwd`
echo "Starting Nemesis front-end server from $NEMESIS_SRC_ROOT/frontends/flux"
cd $NEMESIS_SRC_ROOT/frontends/flux/
npm run start

cd $temp
