#!/usr/bin/env bash
# Usage: nem start
# Summary: Starts up the api, thumbor, and fe servers

set -e

# should we start postgres??

# This won't work, we need to kill the sub-processes when the master process ends
# ( nem api & )

# ( nem thumbor & )

# ( nem fe & )

