#!/usr/bin/env bash
# Usage: nem api {directoryname}
# Summary: Starts up the nemesis api server (pserve)

set -e

echo "Starting Nemesis API server using config: $NEMESIS_SRC_ROOT/nemesis/development.ini"
exec "$NEMESIS_ENV_ROOT/bin/pserve" --reload "$NEMESIS_SRC_ROOT/nemesis/development.ini"
