#!/usr/bin/env bash
# Usage: nem tail [api|fe|thumbor]
# Summary: View the nemesis logs via tail
# Help: By default, all logs are viewed. To view logs
# for a single system, call `nem tail [system]`

set -e

# provide nem completions
if [ "$1" == "--complete" ]; then
    echo "api thumbor fe"
    exit
fi

opt_api="false"
opt_thumbor="false"
opt_fe="false"

for opt in "$@"
do
    case $opt in
        api)
            opt_api="true"
            ;;
        thumbor)
            opt_thumbor="true"
            ;;
        fe)
            opt_fe="true"
            ;;
    esac
done

if [[ "$opt_api" != "true" && "$opt_thumbor" != "true" && "$opt_fe" != "true" ]]; then
    tail -f $NEMESIS_ENV_ROOT/logs/*
else
    if [ "$opt_api" != "true" ]; then
        tail -f $NEMESIS_ENV_ROOT/logs/nemesis.log
    elif [ "$opt_thumbor" != "true" ]; then
        tail -f $NEMESIS_ENV_ROOT/logs/thumbor.log
    elif [ "$opt_fe" != "true" ]; then
        tail -f $NEMESIS_ENV_ROOT/logs/fe-server.log
    fi
fi
